package ru.centralhardware.telegram.znatokiStudentBot.Entity.Enum;

public enum Action {

    EXECUTE_COMMAND_ADD_PUPIL,
    EXECUTE_COMMAND_GET_EMAIL_LIST,
    EXECUTE_COMMAND_GET_ID,
    EXECUTE_COMMAND_GET_TELEPHONE_LIST,
    EXECUTE_COMMAND_GRAND_ACCESS,
    EXECUTE_COMMAND_SEARCH,
    EXECUTE_COMMAND_SEND_EMAIL,
    EXECUTE_COMMAND_SHOW_PAYMENT,
    EXECUTE_COMMAND_SHOW_TIMETABLE,
    EXECUTE_COMMAND_START,
    EXECUTE_COMMAND_USER_INFO,
    PROCESS_CALLBACK_MAILING_STARTED,
    PROCESS_CALLBACK_EMAIL,
    PROCESS_CALLBACK_USER_INFO,
    PROCESS_CALLBACK_EDIT_USER,
    PROCESS_CALLBACK_DELETE_USER,
    PROCESS_CALLBACK_ADD_PAYMENT,
    PROCESS_CALLBACK_ADD_LESSON,
    PROCESS_CALLBACK_LESSON_PROCESS
}
